"""v3_1_0_add_sys_ticket

Revision ID: 2fb31000fb5b
Revises: cf3ef35abed3
Create Date: 2026-05-23 21:58:45.509324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2fb31000fb5b'
down_revision: Union[str, None] = 'cf3ef35abed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_gen')
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否主键',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否查询字段',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否查询字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否主键',
               existing_nullable=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('test_gen',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
