"""v3_1_0_p1_tenant_features

Revision ID: cf3ef35abed3
Revises: 06ee34c848a2
Create Date: 2026-05-23 20:06:48.563318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf3ef35abed3'
down_revision: Union[str, None] = '06ee34c848a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_tenant_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('config_type', sa.String(length=20), nullable=False, comment='配置类型(string/json/int/bool)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenant.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'config_key', name='uq_tenant_config_key'),
    comment='租户配置表'
    )
    op.create_index(op.f('ix_sys_tenant_config_tenant_id'), 'sys_tenant_config', ['tenant_id'], unique=False)
    op.create_table('sys_tenant_quota',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('max_users', sa.Integer(), nullable=False, comment='最大用户数'),
    sa.Column('max_roles', sa.Integer(), nullable=False, comment='最大角色数'),
    sa.Column('max_storage_mb', sa.Integer(), nullable=False, comment='最大存储(MB)'),
    sa.Column('max_depts', sa.Integer(), nullable=False, comment='最大部门数'),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenant.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='租户配额表'
    )
    op.create_index(op.f('ix_sys_tenant_quota_tenant_id'), 'sys_tenant_quota', ['tenant_id'], unique=True)
    op.create_table('sys_tenant_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('menu_id', sa.Integer(), nullable=False, comment='菜单ID'),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menu.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenant.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'menu_id', name='uq_tenant_menu'),
    comment='租户菜单权限表'
    )
    op.create_index(op.f('ix_sys_tenant_menu_menu_id'), 'sys_tenant_menu', ['menu_id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_menu_tenant_id'), 'sys_tenant_menu', ['tenant_id'], unique=False)
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否主键',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否查询字段',
               existing_nullable=False)
    op.alter_column('sys_tenant', 'sort',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='排序',
               existing_nullable=False)
    op.alter_column('sys_user_tenant', 'role',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_comment='租户内角色(owner:拥有者 admin:管理员 member:成员)',
               existing_nullable=False)
    op.alter_column('sys_user_tenant', 'is_default',
               existing_type=mysql.SMALLINT(),
               server_default=None,
               existing_comment='是否默认租户(0:否 1:是)',
               existing_nullable=False)
    op.drop_index('uq_task_workflow_tenant_code', table_name='task_workflow')
    op.create_unique_constraint('uq_task_workflow_code', 'task_workflow', ['tenant_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_workflow_code', 'task_workflow', type_='unique')
    op.create_index('uq_task_workflow_tenant_code', 'task_workflow', ['tenant_id', 'code'], unique=True)
    op.alter_column('sys_user_tenant', 'is_default',
               existing_type=mysql.SMALLINT(),
               server_default=sa.text("'0'"),
               existing_comment='是否默认租户(0:否 1:是)',
               existing_nullable=False)
    op.alter_column('sys_user_tenant', 'role',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'member'"),
               existing_comment='租户内角色(owner:拥有者 admin:管理员 member:成员)',
               existing_nullable=False)
    op.alter_column('sys_tenant', 'sort',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_comment='排序',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否查询字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否主键',
               existing_nullable=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_sys_tenant_menu_tenant_id'), table_name='sys_tenant_menu')
    op.drop_index(op.f('ix_sys_tenant_menu_menu_id'), table_name='sys_tenant_menu')
    op.drop_table('sys_tenant_menu')
    op.drop_index(op.f('ix_sys_tenant_quota_tenant_id'), table_name='sys_tenant_quota')
    op.drop_table('sys_tenant_quota')
    op.drop_index(op.f('ix_sys_tenant_config_tenant_id'), table_name='sys_tenant_config')
    op.drop_table('sys_tenant_config')
    # ### end Alembic commands ###
